version: '3.1'

services:
  database:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.data/mysql:/var/lib/mysql
